### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by lm-jkominek** [flu-crew/parnas#2]
Hi there, PARNAS is a great tool, thank you for creating it! Could you add the description of the 'clusters' option into the tables at the bottom of the main README?  Also, what is the format of the weights file? Do the values have to be in 0-1 range, or can they be arbitrary and will be normalized later?
Thanks in advance for clarification!

**Comment by markin-alex** [comment]
Hi @lm-jkominek - thanks for pointing out that the --clusters description is missing in the README and for using the tool! I will update the README shortly.

For the weights file:
The accepted values are between 0 and 1000. So as long as the weights are below 1000, no normalization is needed. If a taxon is in a tree but not specified in the weights file, its weight will be 1. Note that very small weights (below 1e-8) will be rounded down to 0 to avoid overflow issues.

I hope that helps!

**Comment by lm-jkominek** [comment]
Thank you @markin-alex , appreciate it! How do the weights affect the chances of a leaf being picked as representative? Is it a simple (normalized or not) multiplier of the tree diversity covered by a specific leaf, or is it more nuanced than that? Basically, I'm wondering what would happen if I give leaf A the weight of, say, 100, and leaf B, which is the optimal (from an unweighted perspective) representative a weight of 50. Would leaf A be picked if it covers more than half the diversity of leaf B?

**Comment by markin-alex** [comment]
That's a great question! I think of the weights as indicating where the selections should gravitate to, but not necessarily what should be picked (unless there are few taxa with very high weights and everything else has low weights). The weight of an individual taxon indicates how much it should be represented. Let's say taxon A is at distance d from the closest representative R, chosen by the algorithm. Then, its contribution to the objective function of the algorithm is d times the weight of A. So, the higher the weight of A, the more important it is for the algorithm to pick a representative that is closer to A (decreasing that distance d). But whether A itself will be picked would depend on how well it is positioned in the tree and the weights of taxa around A.

So if you have a clade in a tree with high-weight taxa, that would likely make the algorithm pick at least one taxon from that clade.

I know this is not as intuitive, but I hope that helps!
