### ISSUE TITLE
Add to bioconda

### ISSUE THREAD

**Issue by fdecarpentier** [flu-crew/parnas#5]
I created a pull request to add parnas to bioconda : https://github.com/bioconda/bioconda-recipes/pull/52573

I chose bioconda and not conda-forge because some deps are in bioconda.
Is it ok for you?

Thank you for this great program!
Cheers

Félix

**Comment by markin-alex** [comment]
Thank you, Felix, that's mega!

**Comment by fdecarpentier** [comment]
Thanks!
I limited python to 3.12 for now because of numba. But we should be able to bump to 3.13 soon : https://github.com/numba/numba/issues/9413

By the way, pip installation does not work with 3.13 either for the same reason.

**Comment by markin-alex** [comment]
Yeah, good call! And thanks for checking. Numba team usually catches up fairly quickly with Python versions, but there is definitely a lag. I considered making numba optional, but it speeds up things massively (and will require reimplementing some chunks in pure python). So for now choosing performance!

**Comment by fdecarpentier** [comment]
I'm closing the issue for now and will reopen it when I update the bioconda recipe.

**Comment by fdecarpentier** [comment]
Conda recipe updated https://github.com/bioconda/bioconda-recipes/pull/60565

**Comment by markin-alex** [comment]
Very much appreciate it, Felix!
